# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vr_gui_layout.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(827, 656)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setAttribute(QtCore.Qt.WA_AcceptTouchEvents,True)
        # MainWindow.installEventFilter(MainWindow)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"    border: 2px solid black;\n"
"    height: 30px; \n"
"    width: 261px; \n"
"    background-color: rgb(149, 27, 218);\n"
"    margin: 2px;\n"
"    \n"
"}\n"
"QTabBar::tab:selected{\n"
"    background-color: rgb(218, 58, 245);    \n"
"    margin: 2px;\n"
"}\n"
"QTabWidget{\n"
"    background-color: rgb(149, 27, 218);}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.Manual = QtWidgets.QWidget()
        self.Manual.setAutoFillBackground(False)
        self.Manual.setStyleSheet("QPushButton[objectName^=\"Act\"]{\n"
"    background-color: white;\n"
"    border: none;\n"
"}\n"
"")
        self.Manual.setObjectName("Manual")
        self.multi_modal = QtWidgets.QSlider(self.Manual)
        self.multi_modal.setGeometry(QtCore.QRect(50, 50, 16, 50))
        self.multi_modal.setMaximum(1)
        self.multi_modal.setOrientation(QtCore.Qt.Vertical)
        self.multi_modal.setObjectName("multi_modal")
        self.pulse_mode = QtWidgets.QSlider(self.Manual)
        self.pulse_mode.setGeometry(QtCore.QRect(50, 150, 21, 50))
        self.pulse_mode.setStyleSheet("")
        self.pulse_mode.setMaximum(1)
        self.pulse_mode.setOrientation(QtCore.Qt.Vertical)
        self.pulse_mode.setObjectName("pulse_mode")
        self.threeD_touch = QtWidgets.QSlider(self.Manual)
        self.threeD_touch.setGeometry(QtCore.QRect(170, 50, 16, 50))
        self.threeD_touch.setMaximum(1)
        self.threeD_touch.setOrientation(QtCore.Qt.Vertical)
        self.threeD_touch.setObjectName("threeD_touch")
        self.h_dc = QtWidgets.QSlider(self.Manual)
        self.h_dc.setGeometry(QtCore.QRect(60, 280, 201, 31))
        self.h_dc.setAutoFillBackground(False)
        self.h_dc.setMaximum(100)
        self.h_dc.setSliderPosition(50)
        self.h_dc.setOrientation(QtCore.Qt.Horizontal)
        self.h_dc.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.h_dc.setTickInterval(10)
        self.h_dc.setObjectName("h_dc")
        self.Act1 = QtWidgets.QPushButton(self.Manual)
        self.Act1.setGeometry(QtCore.QRect(430, 50, 50, 50))
        self.Act1.setAutoFillBackground(False)
        self.Act1.setStyleSheet("")
        self.Act1.setText("")
        self.Act1.setCheckable(True)
        self.Act1.setChecked(False)
        self.Act1.setObjectName("Act1")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Act1)
        self.Act2 = QtWidgets.QPushButton(self.Manual)
        self.Act2.setGeometry(QtCore.QRect(480, 50, 50, 50))
        self.Act2.setText("")
        self.Act2.setCheckable(True)
        self.Act2.setObjectName("Act2")
        self.buttonGroup.addButton(self.Act2)
        self.label = QtWidgets.QLabel(self.Manual)
        self.label.setGeometry(QtCore.QRect(40, 0, 67, 61))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.Manual)
        self.label_3.setGeometry(QtCore.QRect(160, 0, 67, 61))
        self.label_3.setObjectName("label_3")
        self.pulse_Hfreq = QtWidgets.QSlider(self.Manual)
        self.pulse_Hfreq.setGeometry(QtCore.QRect(60, 340, 201, 31))
        self.pulse_Hfreq.setMinimum(100)
        self.pulse_Hfreq.setMaximum(1000)
        self.pulse_Hfreq.setSingleStep(10)
        self.pulse_Hfreq.setPageStep(100)
        self.pulse_Hfreq.setProperty("value", 100)
        self.pulse_Hfreq.setOrientation(QtCore.Qt.Horizontal)
        self.pulse_Hfreq.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.pulse_Hfreq.setTickInterval(100)
        self.pulse_Hfreq.setObjectName("pulse_Hfreq")
        self.pulse_duration = QtWidgets.QSlider(self.Manual)
        self.pulse_duration.setGeometry(QtCore.QRect(100, 140, 201, 31))
        self.pulse_duration.setMaximum(5000)
        self.pulse_duration.setSingleStep(10)
        self.pulse_duration.setProperty("value", 500)
        self.pulse_duration.setOrientation(QtCore.Qt.Horizontal)
        self.pulse_duration.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.pulse_duration.setTickInterval(500)
        self.pulse_duration.setObjectName("pulse_duration")
        self.label_2 = QtWidgets.QLabel(self.Manual)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 67, 61))
        self.label_2.setObjectName("label_2")
        self.h_dc_text = QtWidgets.QLabel(self.Manual)
        self.h_dc_text.setGeometry(QtCore.QRect(60, 260, 191, 17))
        self.h_dc_text.setObjectName("h_dc_text")
        self.pulse_Hfreq_text = QtWidgets.QLabel(self.Manual)
        self.pulse_Hfreq_text.setGeometry(QtCore.QRect(60, 320, 201, 17))
        self.pulse_Hfreq_text.setObjectName("pulse_Hfreq_text")
        self.single_pulse_dur_label = QtWidgets.QLabel(self.Manual)
        self.single_pulse_dur_label.setGeometry(QtCore.QRect(100, 110, 181, 25))
        self.single_pulse_dur_label.setObjectName("single_pulse_dur_label")
        self.Act7 = QtWidgets.QPushButton(self.Manual)
        self.Act7.setGeometry(QtCore.QRect(510, 100, 50, 50))
        self.Act7.setText("")
        self.Act7.setCheckable(True)
        self.Act7.setObjectName("Act7")
        self.buttonGroup.addButton(self.Act7)
        self.Act3 = QtWidgets.QPushButton(self.Manual)
        self.Act3.setGeometry(QtCore.QRect(590, 50, 50, 50))
        self.Act3.setText("")
        self.Act3.setCheckable(True)
        self.Act3.setChecked(False)
        self.Act3.setAutoExclusive(True)
        self.Act3.setObjectName("Act3")
        self.buttonGroup.addButton(self.Act3)
        self.Act9 = QtWidgets.QPushButton(self.Manual)
        self.Act9.setGeometry(QtCore.QRect(610, 100, 50, 50))
        self.Act9.setText("")
        self.Act9.setCheckable(True)
        self.Act9.setObjectName("Act9")
        self.buttonGroup.addButton(self.Act9)
        self.Act4 = QtWidgets.QPushButton(self.Manual)
        self.Act4.setGeometry(QtCore.QRect(640, 50, 50, 50))
        self.Act4.setText("")
        self.Act4.setCheckable(True)
        self.Act4.setObjectName("Act4")
        self.buttonGroup.addButton(self.Act4)
        self.Act6 = QtWidgets.QPushButton(self.Manual)
        self.Act6.setGeometry(QtCore.QRect(460, 100, 50, 50))
        self.Act6.setText("")
        self.Act6.setCheckable(True)
        self.Act6.setObjectName("Act6")
        self.buttonGroup.addButton(self.Act6)
        self.Act12 = QtWidgets.QPushButton(self.Manual)
        self.Act12.setGeometry(QtCore.QRect(480, 150, 50, 50))
        self.Act12.setText("")
        self.Act12.setCheckable(True)
        self.Act12.setChecked(False)
        self.Act12.setObjectName("Act12")
        self.buttonGroup.addButton(self.Act12)
        self.Act8 = QtWidgets.QPushButton(self.Manual)
        self.Act8.setGeometry(QtCore.QRect(560, 100, 50, 50))
        self.Act8.setText("")
        self.Act8.setCheckable(True)
        self.Act8.setChecked(False)
        self.Act8.setAutoExclusive(False)
        self.Act8.setObjectName("Act8")
        self.buttonGroup.addButton(self.Act8)
        self.Act36 = QtWidgets.QPushButton(self.Manual)
        self.Act36.setGeometry(QtCore.QRect(640, 350, 50, 50))
        self.Act36.setText("")
        self.Act36.setCheckable(True)
        self.Act36.setObjectName("Act36")
        self.buttonGroup.addButton(self.Act36)
        self.Act5 = QtWidgets.QPushButton(self.Manual)
        self.Act5.setGeometry(QtCore.QRect(410, 100, 50, 50))
        self.Act5.setText("")
        self.Act5.setCheckable(True)
        self.Act5.setObjectName("Act5")
        self.buttonGroup.addButton(self.Act5)
        self.Act14 = QtWidgets.QPushButton(self.Manual)
        self.Act14.setGeometry(QtCore.QRect(580, 150, 50, 50))
        self.Act14.setText("")
        self.Act14.setCheckable(True)
        self.Act14.setObjectName("Act14")
        self.buttonGroup.addButton(self.Act14)
        self.Act10 = QtWidgets.QPushButton(self.Manual)
        self.Act10.setGeometry(QtCore.QRect(660, 100, 50, 50))
        self.Act10.setAutoFillBackground(False)
        self.Act10.setText("")
        self.Act10.setCheckable(True)
        self.Act10.setObjectName("Act10")
        self.buttonGroup.addButton(self.Act10)
        self.Act35 = QtWidgets.QPushButton(self.Manual)
        self.Act35.setGeometry(QtCore.QRect(590, 350, 50, 50))
        self.Act35.setText("")
        self.Act35.setCheckable(True)
        self.Act35.setObjectName("Act35")
        self.buttonGroup.addButton(self.Act35)
        self.Act11 = QtWidgets.QPushButton(self.Manual)
        self.Act11.setGeometry(QtCore.QRect(430, 150, 50, 50))
        self.Act11.setText("")
        self.Act11.setCheckable(True)
        self.Act11.setObjectName("Act11")
        self.buttonGroup.addButton(self.Act11)
        self.Act13 = QtWidgets.QPushButton(self.Manual)
        self.Act13.setGeometry(QtCore.QRect(530, 150, 50, 50))
        self.Act13.setText("")
        self.Act13.setCheckable(True)
        self.Act13.setObjectName("Act13")
        self.buttonGroup.addButton(self.Act13)
        self.Act15 = QtWidgets.QPushButton(self.Manual)
        self.Act15.setGeometry(QtCore.QRect(630, 150, 50, 50))
        self.Act15.setText("")
        self.Act15.setCheckable(True)
        self.Act15.setObjectName("Act15")
        self.buttonGroup.addButton(self.Act15)
        self.Act18 = QtWidgets.QPushButton(self.Manual)
        self.Act18.setGeometry(QtCore.QRect(510, 200, 50, 50))
        self.Act18.setText("")
        self.Act18.setCheckable(True)
        self.Act18.setObjectName("Act18")
        self.buttonGroup.addButton(self.Act18)
        self.Act20 = QtWidgets.QPushButton(self.Manual)
        self.Act20.setGeometry(QtCore.QRect(610, 200, 50, 50))
        self.Act20.setText("")
        self.Act20.setCheckable(True)
        self.Act20.setObjectName("Act20")
        self.buttonGroup.addButton(self.Act20)
        self.Act17 = QtWidgets.QPushButton(self.Manual)
        self.Act17.setGeometry(QtCore.QRect(460, 200, 50, 50))
        self.Act17.setText("")
        self.Act17.setCheckable(True)
        self.Act17.setObjectName("Act17")
        self.buttonGroup.addButton(self.Act17)
        self.Act19 = QtWidgets.QPushButton(self.Manual)
        self.Act19.setGeometry(QtCore.QRect(560, 200, 50, 50))
        self.Act19.setText("")
        self.Act19.setCheckable(True)
        self.Act19.setObjectName("Act19")
        self.buttonGroup.addButton(self.Act19)
        self.Act21 = QtWidgets.QPushButton(self.Manual)
        self.Act21.setGeometry(QtCore.QRect(660, 200, 50, 50))
        self.Act21.setText("")
        self.Act21.setCheckable(True)
        self.Act21.setObjectName("Act21")
        self.buttonGroup.addButton(self.Act21)
        self.Act23 = QtWidgets.QPushButton(self.Manual)
        self.Act23.setGeometry(QtCore.QRect(480, 250, 50, 50))
        self.Act23.setText("")
        self.Act23.setCheckable(True)
        self.Act23.setObjectName("Act23")
        self.buttonGroup.addButton(self.Act23)
        self.Act25 = QtWidgets.QPushButton(self.Manual)
        self.Act25.setGeometry(QtCore.QRect(580, 250, 50, 50))
        self.Act25.setText("")
        self.Act25.setCheckable(True)
        self.Act25.setObjectName("Act25")
        self.buttonGroup.addButton(self.Act25)
        self.Act22 = QtWidgets.QPushButton(self.Manual)
        self.Act22.setGeometry(QtCore.QRect(430, 250, 50, 50))
        self.Act22.setText("")
        self.Act22.setCheckable(True)
        self.Act22.setObjectName("Act22")
        self.buttonGroup.addButton(self.Act22)
        self.Act28 = QtWidgets.QPushButton(self.Manual)
        self.Act28.setGeometry(QtCore.QRect(460, 300, 50, 50))
        self.Act28.setText("")
        self.Act28.setCheckable(True)
        self.Act28.setObjectName("Act28")
        self.buttonGroup.addButton(self.Act28)
        self.Act29 = QtWidgets.QPushButton(self.Manual)
        self.Act29.setGeometry(QtCore.QRect(510, 300, 50, 50))
        self.Act29.setText("")
        self.Act29.setCheckable(True)
        self.Act29.setObjectName("Act29")
        self.buttonGroup.addButton(self.Act29)
        self.Act24 = QtWidgets.QPushButton(self.Manual)
        self.Act24.setGeometry(QtCore.QRect(530, 250, 50, 50))
        self.Act24.setText("")
        self.Act24.setCheckable(True)
        self.Act24.setObjectName("Act24")
        self.buttonGroup.addButton(self.Act24)
        self.Act31 = QtWidgets.QPushButton(self.Manual)
        self.Act31.setGeometry(QtCore.QRect(610, 300, 50, 50))
        self.Act31.setText("")
        self.Act31.setCheckable(True)
        self.Act31.setObjectName("Act31")
        self.buttonGroup.addButton(self.Act31)
        self.Act26 = QtWidgets.QPushButton(self.Manual)
        self.Act26.setGeometry(QtCore.QRect(630, 250, 50, 50))
        self.Act26.setText("")
        self.Act26.setCheckable(True)
        self.Act26.setObjectName("Act26")
        self.buttonGroup.addButton(self.Act26)
        self.Act30 = QtWidgets.QPushButton(self.Manual)
        self.Act30.setGeometry(QtCore.QRect(560, 300, 50, 50))
        self.Act30.setText("")
        self.Act30.setCheckable(True)
        self.Act30.setObjectName("Act30")
        self.buttonGroup.addButton(self.Act30)
        self.Act32 = QtWidgets.QPushButton(self.Manual)
        self.Act32.setGeometry(QtCore.QRect(660, 300, 50, 50))
        self.Act32.setText("")
        self.Act32.setCheckable(True)
        self.Act32.setObjectName("Act32")
        self.buttonGroup.addButton(self.Act32)
        self.Act27 = QtWidgets.QPushButton(self.Manual)
        self.Act27.setGeometry(QtCore.QRect(410, 300, 50, 50))
        self.Act27.setText("")
        self.Act27.setCheckable(True)
        self.Act27.setObjectName("Act27")
        self.buttonGroup.addButton(self.Act27)
        self.Act16 = QtWidgets.QPushButton(self.Manual)
        self.Act16.setGeometry(QtCore.QRect(410, 200, 50, 50))
        self.Act16.setText("")
        self.Act16.setCheckable(True)
        self.Act16.setObjectName("Act16")
        self.buttonGroup.addButton(self.Act16)
        self.Act33 = QtWidgets.QPushButton(self.Manual)
        self.Act33.setGeometry(QtCore.QRect(430, 350, 50, 50))
        self.Act33.setText("")
        self.Act33.setCheckable(True)
        self.Act33.setObjectName("Act33")
        self.buttonGroup.addButton(self.Act33)
        self.Act34 = QtWidgets.QPushButton(self.Manual)
        self.Act34.setGeometry(QtCore.QRect(480, 350, 50, 50))
        self.Act34.setText("")
        self.Act34.setCheckable(True)
        self.Act34.setObjectName("Act34")
        self.buttonGroup.addButton(self.Act34)
        self.all_off = QtWidgets.QPushButton(self.Manual)
        self.all_off.setGeometry(QtCore.QRect(540, 10, 91, 25))
        self.all_off.setObjectName("all_off")
        self.label_4 = QtWidgets.QLabel(self.Manual)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 91, 41))
        self.label_4.setObjectName("label_4")
        self.hf_mod = QtWidgets.QRadioButton(self.Manual)
        self.hf_mod.setGeometry(QtCore.QRect(30, 230, 241, 23))
        self.hf_mod.setAutoExclusive(False)
        self.hf_mod.setObjectName("hf_mod")
        self.lf_mod = QtWidgets.QRadioButton(self.Manual)
        self.lf_mod.setGeometry(QtCore.QRect(30, 380, 241, 40))
        self.lf_mod.setAutoExclusive(False)
        self.lf_mod.setObjectName("lf_mod")
        self.single_pulse_dur_text = QtWidgets.QLineEdit(self.Manual)
        self.single_pulse_dur_text.setGeometry(QtCore.QRect(280, 110, 61, 25))
        self.single_pulse_dur_text.setObjectName("single_pulse_dur_text")
        self.pulse_Lfreq_text = QtWidgets.QLabel(self.Manual)
        self.pulse_Lfreq_text.setGeometry(QtCore.QRect(60, 490, 241, 17))
        self.pulse_Lfreq_text.setObjectName("pulse_Lfreq_text")
        self.pulse_Lfreq = QtWidgets.QSlider(self.Manual)
        self.pulse_Lfreq.setGeometry(QtCore.QRect(60, 510, 201, 31))
        self.pulse_Lfreq.setProperty("value", 2)
        self.pulse_Lfreq.setOrientation(QtCore.Qt.Horizontal)
        self.pulse_Lfreq.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.pulse_Lfreq.setTickInterval(10)
        self.pulse_Lfreq.setObjectName("pulse_Lfreq")
        self.l_dc = QtWidgets.QSlider(self.Manual)
        self.l_dc.setGeometry(QtCore.QRect(60, 450, 201, 31))
        self.l_dc.setAutoFillBackground(False)
        self.l_dc.setMaximum(100)
        self.l_dc.setProperty("value", 50)
        self.l_dc.setOrientation(QtCore.Qt.Horizontal)
        self.l_dc.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.l_dc.setTickInterval(10)
        self.l_dc.setObjectName("l_dc")
        self.l_dc_text = QtWidgets.QLabel(self.Manual)
        self.l_dc_text.setGeometry(QtCore.QRect(60, 430, 191, 17))
        self.l_dc_text.setObjectName("l_dc_text")
        self.set_time = QtWidgets.QPushButton(self.Manual)
        self.set_time.setGeometry(QtCore.QRect(170, 180, 91, 41))
        self.set_time.setObjectName("set_time")
        self.active_selected = QtWidgets.QPushButton(self.Manual)
        self.active_selected.setEnabled(False)
        self.active_selected.setGeometry(QtCore.QRect(270, 20, 131, 41))
        self.active_selected.setObjectName("active_selected")
        self.append_preset = QtWidgets.QPushButton(self.Manual)
        self.append_preset.setGeometry(QtCore.QRect(470, 440, 131, 41))
        self.append_preset.setCheckable(True)
        self.append_preset.setObjectName("append_preset")
        self.append_preset_name = QtWidgets.QLineEdit(self.Manual)
        self.append_preset_name.setGeometry(QtCore.QRect(610, 450, 113, 25))
        self.append_preset_name.setObjectName("append_preset_name")
        self.tabWidget.addTab(self.Manual, "")
        self.Automatic = QtWidgets.QWidget()
        self.Automatic.setObjectName("Automatic")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Automatic)
        self.verticalLayout.setObjectName("verticalLayout")
        self.preset_button = QtWidgets.QPushButton(self.Automatic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preset_button.sizePolicy().hasHeightForWidth())
        self.preset_button.setSizePolicy(sizePolicy)
        self.preset_button.setMinimumSize(QtCore.QSize(0, 60))
        self.preset_button.setMaximumSize(QtCore.QSize(16777215, 500))
        self.preset_button.setObjectName("preset_button")
        self.verticalLayout.addWidget(self.preset_button)
        self.tab_position = QtWidgets.QTabWidget(self.Automatic)
        self.tab_position.setStyleSheet("QTabBar::tab { \n"
"    height: 120px; \n"
"    width: 120px; \n"
"}\n"
"QTabBar::tab:first {\n"
"    border-image: url(/home/rschloen/haptic_vr/GUI//img/preset_stomach.png);\n"
"}\n"
"\n"
"")
        self.tab_position.setTabPosition(QtWidgets.QTabWidget.West)
        self.tab_position.setElideMode(QtCore.Qt.ElideLeft)
        self.tab_position.setObjectName("tab_position")
        self.Position1 = QtWidgets.QWidget()
        self.Position1.setStyleSheet("")
        self.Position1.setObjectName("Position1")
        self.Act7_2 = QtWidgets.QPushButton(self.Position1)
        self.Act7_2.setGeometry(QtCore.QRect(300, 80, 51, 41))
        self.Act7_2.setText("")
        self.Act7_2.setCheckable(True)
        self.Act7_2.setObjectName("Act7_2")
        self.Act8_2 = QtWidgets.QPushButton(self.Position1)
        self.Act8_2.setGeometry(QtCore.QRect(360, 80, 51, 41))
        self.Act8_2.setText("")
        self.Act8_2.setCheckable(True)
        self.Act8_2.setObjectName("Act8_2")
        self.Act33_2 = QtWidgets.QPushButton(self.Position1)
        self.Act33_2.setGeometry(QtCore.QRect(210, 330, 51, 41))
        self.Act33_2.setText("")
        self.Act33_2.setCheckable(True)
        self.Act33_2.setObjectName("Act33_2")
        self.Act1_2 = QtWidgets.QPushButton(self.Position1)
        self.Act1_2.setGeometry(QtCore.QRect(220, 30, 51, 41))
        self.Act1_2.setText("")
        self.Act1_2.setCheckable(True)
        self.Act1_2.setObjectName("Act1_2")
        self.Act6_2 = QtWidgets.QPushButton(self.Position1)
        self.Act6_2.setGeometry(QtCore.QRect(240, 80, 51, 41))
        self.Act6_2.setText("")
        self.Act6_2.setCheckable(True)
        self.Act6_2.setObjectName("Act6_2")
        self.Act27_2 = QtWidgets.QPushButton(self.Position1)
        self.Act27_2.setGeometry(QtCore.QRect(180, 280, 51, 41))
        self.Act27_2.setText("")
        self.Act27_2.setCheckable(True)
        self.Act27_2.setObjectName("Act27_2")
        self.Act28_2 = QtWidgets.QPushButton(self.Position1)
        self.Act28_2.setGeometry(QtCore.QRect(240, 280, 51, 41))
        self.Act28_2.setText("")
        self.Act28_2.setCheckable(True)
        self.Act28_2.setObjectName("Act28_2")
        self.Act5_2 = QtWidgets.QPushButton(self.Position1)
        self.Act5_2.setGeometry(QtCore.QRect(180, 80, 51, 41))
        self.Act5_2.setText("")
        self.Act5_2.setCheckable(True)
        self.Act5_2.setObjectName("Act5_2")
        self.Act34_2 = QtWidgets.QPushButton(self.Position1)
        self.Act34_2.setGeometry(QtCore.QRect(270, 330, 51, 41))
        self.Act34_2.setText("")
        self.Act34_2.setCheckable(True)
        self.Act34_2.setObjectName("Act34_2")
        self.Act18_2 = QtWidgets.QPushButton(self.Position1)
        self.Act18_2.setGeometry(QtCore.QRect(300, 180, 51, 41))
        self.Act18_2.setText("")
        self.Act18_2.setCheckable(True)
        self.Act18_2.setObjectName("Act18_2")
        self.Act15_2 = QtWidgets.QPushButton(self.Position1)
        self.Act15_2.setGeometry(QtCore.QRect(450, 130, 51, 41))
        self.Act15_2.setText("")
        self.Act15_2.setCheckable(True)
        self.Act15_2.setObjectName("Act15_2")
        self.Act20_2 = QtWidgets.QPushButton(self.Position1)
        self.Act20_2.setGeometry(QtCore.QRect(420, 180, 51, 41))
        self.Act20_2.setText("")
        self.Act20_2.setCheckable(True)
        self.Act20_2.setObjectName("Act20_2")
        self.Act32_2 = QtWidgets.QPushButton(self.Position1)
        self.Act32_2.setGeometry(QtCore.QRect(480, 280, 51, 41))
        self.Act32_2.setText("")
        self.Act32_2.setCheckable(True)
        self.Act32_2.setObjectName("Act32_2")
        self.Act2_2 = QtWidgets.QPushButton(self.Position1)
        self.Act2_2.setGeometry(QtCore.QRect(280, 30, 51, 41))
        self.Act2_2.setText("")
        self.Act2_2.setCheckable(True)
        self.Act2_2.setObjectName("Act2_2")
        self.Act29_2 = QtWidgets.QPushButton(self.Position1)
        self.Act29_2.setGeometry(QtCore.QRect(300, 280, 51, 41))
        self.Act29_2.setText("")
        self.Act29_2.setCheckable(True)
        self.Act29_2.setObjectName("Act29_2")
        self.Act16_2 = QtWidgets.QPushButton(self.Position1)
        self.Act16_2.setGeometry(QtCore.QRect(180, 180, 51, 41))
        self.Act16_2.setText("")
        self.Act16_2.setCheckable(True)
        self.Act16_2.setObjectName("Act16_2")
        self.Act30_2 = QtWidgets.QPushButton(self.Position1)
        self.Act30_2.setGeometry(QtCore.QRect(360, 280, 51, 41))
        self.Act30_2.setText("")
        self.Act30_2.setCheckable(True)
        self.Act30_2.setObjectName("Act30_2")
        self.Act31_2 = QtWidgets.QPushButton(self.Position1)
        self.Act31_2.setGeometry(QtCore.QRect(420, 280, 51, 41))
        self.Act31_2.setText("")
        self.Act31_2.setCheckable(True)
        self.Act31_2.setObjectName("Act31_2")
        self.Act35_2 = QtWidgets.QPushButton(self.Position1)
        self.Act35_2.setGeometry(QtCore.QRect(390, 330, 51, 41))
        self.Act35_2.setText("")
        self.Act35_2.setCheckable(True)
        self.Act35_2.setObjectName("Act35_2")
        self.Act24_2 = QtWidgets.QPushButton(self.Position1)
        self.Act24_2.setGeometry(QtCore.QRect(330, 230, 51, 41))
        self.Act24_2.setText("")
        self.Act24_2.setCheckable(True)
        self.Act24_2.setObjectName("Act24_2")
        self.Act3_2 = QtWidgets.QPushButton(self.Position1)
        self.Act3_2.setGeometry(QtCore.QRect(390, 30, 51, 41))
        self.Act3_2.setText("")
        self.Act3_2.setCheckable(True)
        self.Act3_2.setObjectName("Act3_2")
        self.Act14_2 = QtWidgets.QPushButton(self.Position1)
        self.Act14_2.setGeometry(QtCore.QRect(390, 130, 51, 41))
        self.Act14_2.setText("")
        self.Act14_2.setCheckable(True)
        self.Act14_2.setObjectName("Act14_2")
        self.Act25_2 = QtWidgets.QPushButton(self.Position1)
        self.Act25_2.setGeometry(QtCore.QRect(390, 230, 51, 41))
        self.Act25_2.setText("")
        self.Act25_2.setCheckable(True)
        self.Act25_2.setObjectName("Act25_2")
        self.Act10_2 = QtWidgets.QPushButton(self.Position1)
        self.Act10_2.setGeometry(QtCore.QRect(480, 80, 51, 41))
        self.Act10_2.setText("")
        self.Act10_2.setCheckable(True)
        self.Act10_2.setObjectName("Act10_2")
        self.Act21_2 = QtWidgets.QPushButton(self.Position1)
        self.Act21_2.setGeometry(QtCore.QRect(480, 180, 51, 41))
        self.Act21_2.setText("")
        self.Act21_2.setCheckable(True)
        self.Act21_2.setObjectName("Act21_2")
        self.Act23_2 = QtWidgets.QPushButton(self.Position1)
        self.Act23_2.setGeometry(QtCore.QRect(270, 230, 51, 41))
        self.Act23_2.setText("")
        self.Act23_2.setCheckable(True)
        self.Act23_2.setObjectName("Act23_2")
        self.Act19_2 = QtWidgets.QPushButton(self.Position1)
        self.Act19_2.setGeometry(QtCore.QRect(360, 180, 51, 41))
        self.Act19_2.setText("")
        self.Act19_2.setCheckable(True)
        self.Act19_2.setObjectName("Act19_2")
        self.Act4_2 = QtWidgets.QPushButton(self.Position1)
        self.Act4_2.setGeometry(QtCore.QRect(450, 30, 51, 41))
        self.Act4_2.setText("")
        self.Act4_2.setCheckable(True)
        self.Act4_2.setObjectName("Act4_2")
        self.Act26_2 = QtWidgets.QPushButton(self.Position1)
        self.Act26_2.setGeometry(QtCore.QRect(450, 230, 51, 41))
        self.Act26_2.setText("")
        self.Act26_2.setCheckable(True)
        self.Act26_2.setObjectName("Act26_2")
        self.Act36_2 = QtWidgets.QPushButton(self.Position1)
        self.Act36_2.setGeometry(QtCore.QRect(450, 330, 51, 41))
        self.Act36_2.setText("")
        self.Act36_2.setCheckable(True)
        self.Act36_2.setObjectName("Act36_2")
        self.Act11_2 = QtWidgets.QPushButton(self.Position1)
        self.Act11_2.setGeometry(QtCore.QRect(210, 130, 51, 41))
        self.Act11_2.setText("")
        self.Act11_2.setCheckable(True)
        self.Act11_2.setObjectName("Act11_2")
        self.Act17_2 = QtWidgets.QPushButton(self.Position1)
        self.Act17_2.setGeometry(QtCore.QRect(240, 180, 51, 41))
        self.Act17_2.setText("")
        self.Act17_2.setCheckable(True)
        self.Act17_2.setObjectName("Act17_2")
        self.Act9_2 = QtWidgets.QPushButton(self.Position1)
        self.Act9_2.setGeometry(QtCore.QRect(420, 80, 51, 41))
        self.Act9_2.setText("")
        self.Act9_2.setCheckable(True)
        self.Act9_2.setObjectName("Act9_2")
        self.Act13_2 = QtWidgets.QPushButton(self.Position1)
        self.Act13_2.setGeometry(QtCore.QRect(330, 130, 51, 41))
        self.Act13_2.setText("")
        self.Act13_2.setCheckable(True)
        self.Act13_2.setObjectName("Act13_2")
        self.Act12_2 = QtWidgets.QPushButton(self.Position1)
        self.Act12_2.setGeometry(QtCore.QRect(270, 130, 51, 41))
        self.Act12_2.setText("")
        self.Act12_2.setCheckable(True)
        self.Act12_2.setChecked(False)
        self.Act12_2.setObjectName("Act12_2")
        self.Act22_2 = QtWidgets.QPushButton(self.Position1)
        self.Act22_2.setGeometry(QtCore.QRect(210, 230, 51, 41))
        self.Act22_2.setText("")
        self.Act22_2.setCheckable(True)
        self.Act22_2.setObjectName("Act22_2")
        self.tab_position.addTab(self.Position1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Act24_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act24_8.setGeometry(QtCore.QRect(340, 280, 51, 41))
        self.Act24_8.setText("")
        self.Act24_8.setCheckable(True)
        self.Act24_8.setObjectName("Act24_8")
        self.Act11_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act11_8.setGeometry(QtCore.QRect(220, 180, 51, 41))
        self.Act11_8.setText("")
        self.Act11_8.setCheckable(True)
        self.Act11_8.setObjectName("Act11_8")
        self.Act17_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act17_8.setGeometry(QtCore.QRect(220, 230, 51, 41))
        self.Act17_8.setText("")
        self.Act17_8.setCheckable(True)
        self.Act17_8.setObjectName("Act17_8")
        self.Act10_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act10_8.setGeometry(QtCore.QRect(460, 130, 51, 41))
        self.Act10_8.setText("")
        self.Act10_8.setCheckable(True)
        self.Act10_8.setObjectName("Act10_8")
        self.Act2_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act2_8.setGeometry(QtCore.QRect(220, 80, 51, 41))
        self.Act2_8.setText("")
        self.Act2_8.setCheckable(True)
        self.Act2_8.setObjectName("Act2_8")
        self.Act30_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act30_8.setGeometry(QtCore.QRect(340, 330, 51, 41))
        self.Act30_8.setText("")
        self.Act30_8.setCheckable(True)
        self.Act30_8.setObjectName("Act30_8")
        self.Act1_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act1_8.setGeometry(QtCore.QRect(160, 110, 51, 41))
        self.Act1_8.setText("")
        self.Act1_8.setCheckable(True)
        self.Act1_8.setObjectName("Act1_8")
        self.Act34_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act34_8.setGeometry(QtCore.QRect(520, 260, 51, 41))
        self.Act34_8.setText("")
        self.Act34_8.setCheckable(True)
        self.Act34_8.setObjectName("Act34_8")
        self.Act36_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act36_8.setGeometry(QtCore.QRect(520, 110, 51, 41))
        self.Act36_8.setText("")
        self.Act36_8.setCheckable(True)
        self.Act36_8.setObjectName("Act36_8")
        self.Act12_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act12_8.setGeometry(QtCore.QRect(280, 160, 51, 41))
        self.Act12_8.setText("")
        self.Act12_8.setCheckable(True)
        self.Act12_8.setChecked(False)
        self.Act12_8.setObjectName("Act12_8")
        self.Act21_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act21_8.setGeometry(QtCore.QRect(460, 230, 51, 41))
        self.Act21_8.setText("")
        self.Act21_8.setCheckable(True)
        self.Act21_8.setObjectName("Act21_8")
        self.Act31_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act31_8.setGeometry(QtCore.QRect(400, 310, 51, 41))
        self.Act31_8.setText("")
        self.Act31_8.setCheckable(True)
        self.Act31_8.setObjectName("Act31_8")
        self.Act6_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act6_8.setGeometry(QtCore.QRect(220, 130, 51, 41))
        self.Act6_8.setText("")
        self.Act6_8.setCheckable(True)
        self.Act6_8.setObjectName("Act6_8")
        self.Act8_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act8_8.setGeometry(QtCore.QRect(340, 130, 51, 41))
        self.Act8_8.setText("")
        self.Act8_8.setCheckable(True)
        self.Act8_8.setObjectName("Act8_8")
        self.Act16_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act16_8.setGeometry(QtCore.QRect(160, 260, 51, 41))
        self.Act16_8.setText("")
        self.Act16_8.setCheckable(True)
        self.Act16_8.setObjectName("Act16_8")
        self.Act18_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act18_8.setGeometry(QtCore.QRect(280, 210, 51, 41))
        self.Act18_8.setText("")
        self.Act18_8.setCheckable(True)
        self.Act18_8.setObjectName("Act18_8")
        self.Act15_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act15_8.setGeometry(QtCore.QRect(460, 180, 51, 41))
        self.Act15_8.setText("")
        self.Act15_8.setCheckable(True)
        self.Act15_8.setObjectName("Act15_8")
        self.Act9_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act9_8.setGeometry(QtCore.QRect(400, 110, 51, 41))
        self.Act9_8.setText("")
        self.Act9_8.setCheckable(True)
        self.Act9_8.setObjectName("Act9_8")
        self.Act4_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act4_8.setGeometry(QtCore.QRect(460, 80, 51, 41))
        self.Act4_8.setText("")
        self.Act4_8.setCheckable(True)
        self.Act4_8.setObjectName("Act4_8")
        self.Act19_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act19_8.setGeometry(QtCore.QRect(340, 230, 51, 41))
        self.Act19_8.setText("")
        self.Act19_8.setCheckable(True)
        self.Act19_8.setObjectName("Act19_8")
        self.Act14_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act14_8.setGeometry(QtCore.QRect(400, 160, 51, 41))
        self.Act14_8.setText("")
        self.Act14_8.setCheckable(True)
        self.Act14_8.setObjectName("Act14_8")
        self.Act26_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act26_8.setGeometry(QtCore.QRect(460, 280, 51, 41))
        self.Act26_8.setText("")
        self.Act26_8.setCheckable(True)
        self.Act26_8.setObjectName("Act26_8")
        self.Act5_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act5_8.setGeometry(QtCore.QRect(160, 160, 51, 41))
        self.Act5_8.setText("")
        self.Act5_8.setCheckable(True)
        self.Act5_8.setObjectName("Act5_8")
        self.Act29_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act29_8.setGeometry(QtCore.QRect(280, 310, 51, 41))
        self.Act29_8.setText("")
        self.Act29_8.setCheckable(True)
        self.Act29_8.setObjectName("Act29_8")
        self.Act33_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act33_8.setGeometry(QtCore.QRect(520, 310, 51, 41))
        self.Act33_8.setText("")
        self.Act33_8.setCheckable(True)
        self.Act33_8.setObjectName("Act33_8")
        self.Act23_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act23_8.setGeometry(QtCore.QRect(280, 260, 51, 41))
        self.Act23_8.setText("")
        self.Act23_8.setCheckable(True)
        self.Act23_8.setObjectName("Act23_8")
        self.Act20_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act20_8.setGeometry(QtCore.QRect(400, 210, 51, 41))
        self.Act20_8.setText("")
        self.Act20_8.setCheckable(True)
        self.Act20_8.setObjectName("Act20_8")
        self.Act25_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act25_8.setGeometry(QtCore.QRect(400, 260, 51, 41))
        self.Act25_8.setText("")
        self.Act25_8.setCheckable(True)
        self.Act25_8.setObjectName("Act25_8")
        self.Act13_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act13_8.setGeometry(QtCore.QRect(340, 180, 51, 41))
        self.Act13_8.setText("")
        self.Act13_8.setCheckable(True)
        self.Act13_8.setObjectName("Act13_8")
        self.Act7_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act7_8.setGeometry(QtCore.QRect(280, 110, 51, 41))
        self.Act7_8.setText("")
        self.Act7_8.setCheckable(True)
        self.Act7_8.setObjectName("Act7_8")
        self.Act22_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act22_8.setGeometry(QtCore.QRect(220, 280, 51, 41))
        self.Act22_8.setText("")
        self.Act22_8.setCheckable(True)
        self.Act22_8.setObjectName("Act22_8")
        self.Act27_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act27_8.setGeometry(QtCore.QRect(160, 310, 51, 41))
        self.Act27_8.setText("")
        self.Act27_8.setCheckable(True)
        self.Act27_8.setObjectName("Act27_8")
        self.Act35_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act35_8.setGeometry(QtCore.QRect(520, 160, 51, 41))
        self.Act35_8.setText("")
        self.Act35_8.setCheckable(True)
        self.Act35_8.setObjectName("Act35_8")
        self.Act3_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act3_8.setGeometry(QtCore.QRect(340, 80, 51, 41))
        self.Act3_8.setText("")
        self.Act3_8.setCheckable(True)
        self.Act3_8.setObjectName("Act3_8")
        self.Act32_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act32_8.setGeometry(QtCore.QRect(460, 330, 51, 41))
        self.Act32_8.setText("")
        self.Act32_8.setCheckable(True)
        self.Act32_8.setObjectName("Act32_8")
        self.Act28_8 = QtWidgets.QPushButton(self.tab_2)
        self.Act28_8.setGeometry(QtCore.QRect(220, 330, 51, 41))
        self.Act28_8.setText("")
        self.Act28_8.setCheckable(True)
        self.Act28_8.setObjectName("Act28_8")
        self.sweep_type = QtWidgets.QComboBox(self.tab_2)
        self.sweep_type.setGeometry(QtCore.QRect(20, 30, 181, 41))
        self.sweep_type.setObjectName("sweep_type")
        self.sweep_type.addItem("")
        self.sweep_type.addItem("")
        self.sweep_type.addItem("")
        self.sweep_type.addItem("")
        self.sweep_type.addItem("")
        self.sweep_type.addItem("")
        self.sweep_type.addItem("")
        self.sweep_type.addItem("")
        self.sweep_type.addItem("")
        self.sweep_type.addItem("")
        self.tab_position.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.Act14_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act14_4.setGeometry(QtCore.QRect(400, 160, 51, 41))
        self.Act14_4.setText("")
        self.Act14_4.setCheckable(True)
        self.Act14_4.setObjectName("Act14_4")
        self.Act24_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act24_4.setGeometry(QtCore.QRect(340, 280, 51, 41))
        self.Act24_4.setText("")
        self.Act24_4.setCheckable(True)
        self.Act24_4.setObjectName("Act24_4")
        self.Act2_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act2_4.setGeometry(QtCore.QRect(220, 80, 51, 41))
        self.Act2_4.setText("")
        self.Act2_4.setCheckable(True)
        self.Act2_4.setObjectName("Act2_4")
        self.Act7_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act7_4.setGeometry(QtCore.QRect(280, 110, 51, 41))
        self.Act7_4.setText("")
        self.Act7_4.setCheckable(True)
        self.Act7_4.setObjectName("Act7_4")
        self.Act25_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act25_4.setGeometry(QtCore.QRect(400, 260, 51, 41))
        self.Act25_4.setText("")
        self.Act25_4.setCheckable(True)
        self.Act25_4.setObjectName("Act25_4")
        self.Act20_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act20_4.setGeometry(QtCore.QRect(400, 210, 51, 41))
        self.Act20_4.setText("")
        self.Act20_4.setCheckable(True)
        self.Act20_4.setObjectName("Act20_4")
        self.Act33_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act33_4.setGeometry(QtCore.QRect(520, 310, 51, 41))
        self.Act33_4.setText("")
        self.Act33_4.setCheckable(True)
        self.Act33_4.setObjectName("Act33_4")
        self.Act13_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act13_4.setGeometry(QtCore.QRect(340, 180, 51, 41))
        self.Act13_4.setText("")
        self.Act13_4.setCheckable(True)
        self.Act13_4.setObjectName("Act13_4")
        self.Act5_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act5_4.setGeometry(QtCore.QRect(160, 160, 51, 41))
        self.Act5_4.setText("")
        self.Act5_4.setCheckable(True)
        self.Act5_4.setObjectName("Act5_4")
        self.Act27_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act27_4.setGeometry(QtCore.QRect(160, 310, 51, 41))
        self.Act27_4.setText("")
        self.Act27_4.setCheckable(True)
        self.Act27_4.setObjectName("Act27_4")
        self.Act22_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act22_4.setGeometry(QtCore.QRect(220, 280, 51, 41))
        self.Act22_4.setText("")
        self.Act22_4.setCheckable(True)
        self.Act22_4.setObjectName("Act22_4")
        self.Act23_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act23_4.setGeometry(QtCore.QRect(280, 260, 51, 41))
        self.Act23_4.setText("")
        self.Act23_4.setCheckable(True)
        self.Act23_4.setObjectName("Act23_4")
        self.Act30_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act30_4.setGeometry(QtCore.QRect(340, 330, 51, 41))
        self.Act30_4.setText("")
        self.Act30_4.setCheckable(True)
        self.Act30_4.setObjectName("Act30_4")
        self.Act31_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act31_4.setGeometry(QtCore.QRect(400, 310, 51, 41))
        self.Act31_4.setText("")
        self.Act31_4.setCheckable(True)
        self.Act31_4.setObjectName("Act31_4")
        self.Act3_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act3_4.setGeometry(QtCore.QRect(340, 80, 51, 41))
        self.Act3_4.setText("")
        self.Act3_4.setCheckable(True)
        self.Act3_4.setObjectName("Act3_4")
        self.Act10_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act10_4.setGeometry(QtCore.QRect(460, 130, 51, 41))
        self.Act10_4.setText("")
        self.Act10_4.setCheckable(True)
        self.Act10_4.setObjectName("Act10_4")
        self.Act16_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act16_4.setGeometry(QtCore.QRect(160, 260, 51, 41))
        self.Act16_4.setText("")
        self.Act16_4.setCheckable(True)
        self.Act16_4.setObjectName("Act16_4")
        self.Act18_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act18_4.setGeometry(QtCore.QRect(280, 210, 51, 41))
        self.Act18_4.setText("")
        self.Act18_4.setCheckable(True)
        self.Act18_4.setObjectName("Act18_4")
        self.Act36_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act36_4.setGeometry(QtCore.QRect(520, 110, 51, 41))
        self.Act36_4.setText("")
        self.Act36_4.setCheckable(True)
        self.Act36_4.setObjectName("Act36_4")
        self.Act6_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act6_4.setGeometry(QtCore.QRect(220, 130, 51, 41))
        self.Act6_4.setText("")
        self.Act6_4.setCheckable(True)
        self.Act6_4.setObjectName("Act6_4")
        self.Act4_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act4_4.setGeometry(QtCore.QRect(460, 80, 51, 41))
        self.Act4_4.setText("")
        self.Act4_4.setCheckable(True)
        self.Act4_4.setObjectName("Act4_4")
        self.Act17_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act17_4.setGeometry(QtCore.QRect(220, 230, 51, 41))
        self.Act17_4.setText("")
        self.Act17_4.setCheckable(True)
        self.Act17_4.setObjectName("Act17_4")
        self.Act28_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act28_4.setGeometry(QtCore.QRect(220, 330, 51, 41))
        self.Act28_4.setText("")
        self.Act28_4.setCheckable(True)
        self.Act28_4.setObjectName("Act28_4")
        self.Act29_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act29_4.setGeometry(QtCore.QRect(280, 310, 51, 41))
        self.Act29_4.setText("")
        self.Act29_4.setCheckable(True)
        self.Act29_4.setObjectName("Act29_4")
        self.Act34_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act34_4.setGeometry(QtCore.QRect(520, 260, 51, 41))
        self.Act34_4.setText("")
        self.Act34_4.setCheckable(True)
        self.Act34_4.setObjectName("Act34_4")
        self.Act32_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act32_4.setGeometry(QtCore.QRect(460, 330, 51, 41))
        self.Act32_4.setText("")
        self.Act32_4.setCheckable(True)
        self.Act32_4.setObjectName("Act32_4")
        self.Act21_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act21_4.setGeometry(QtCore.QRect(460, 230, 51, 41))
        self.Act21_4.setText("")
        self.Act21_4.setCheckable(True)
        self.Act21_4.setObjectName("Act21_4")
        self.Act15_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act15_4.setGeometry(QtCore.QRect(460, 180, 51, 41))
        self.Act15_4.setText("")
        self.Act15_4.setCheckable(True)
        self.Act15_4.setObjectName("Act15_4")
        self.Act8_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act8_4.setGeometry(QtCore.QRect(340, 130, 51, 41))
        self.Act8_4.setText("")
        self.Act8_4.setCheckable(True)
        self.Act8_4.setObjectName("Act8_4")
        self.Act26_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act26_4.setGeometry(QtCore.QRect(460, 280, 51, 41))
        self.Act26_4.setText("")
        self.Act26_4.setCheckable(True)
        self.Act26_4.setObjectName("Act26_4")
        self.Act19_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act19_4.setGeometry(QtCore.QRect(340, 230, 51, 41))
        self.Act19_4.setText("")
        self.Act19_4.setCheckable(True)
        self.Act19_4.setObjectName("Act19_4")
        self.Act35_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act35_4.setGeometry(QtCore.QRect(520, 160, 51, 41))
        self.Act35_4.setText("")
        self.Act35_4.setCheckable(True)
        self.Act35_4.setObjectName("Act35_4")
        self.Act12_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act12_4.setGeometry(QtCore.QRect(280, 160, 51, 41))
        self.Act12_4.setText("")
        self.Act12_4.setCheckable(True)
        self.Act12_4.setChecked(False)
        self.Act12_4.setObjectName("Act12_4")
        self.Act11_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act11_4.setGeometry(QtCore.QRect(220, 180, 51, 41))
        self.Act11_4.setText("")
        self.Act11_4.setCheckable(True)
        self.Act11_4.setObjectName("Act11_4")
        self.Act1_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act1_4.setGeometry(QtCore.QRect(160, 110, 51, 41))
        self.Act1_4.setText("")
        self.Act1_4.setCheckable(True)
        self.Act1_4.setObjectName("Act1_4")
        self.Act9_4 = QtWidgets.QPushButton(self.tab_3)
        self.Act9_4.setGeometry(QtCore.QRect(400, 110, 51, 41))
        self.Act9_4.setText("")
        self.Act9_4.setCheckable(True)
        self.Act9_4.setObjectName("Act9_4")
        self.tab_position.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tab_position)
        self.tabWidget.addTab(self.Automatic, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.PORT = QtWidgets.QLabel(self.Settings)
        self.PORT.setGeometry(QtCore.QRect(180, 20, 241, 21))
        self.PORT.setObjectName("PORT")
        self.rf_power = QtWidgets.QSlider(self.Settings)
        self.rf_power.setGeometry(QtCore.QRect(40, 170, 160, 21))
        self.rf_power.setMinimum(4)
        self.rf_power.setMaximum(12)
        self.rf_power.setProperty("value", 4)
        self.rf_power.setSliderPosition(4)
        self.rf_power.setOrientation(QtCore.Qt.Horizontal)
        self.rf_power.setInvertedAppearance(False)
        self.rf_power.setInvertedControls(False)
        self.rf_power.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.rf_power.setTickInterval(1)
        self.rf_power.setObjectName("rf_power")
        self.label_8 = QtWidgets.QLabel(self.Settings)
        self.label_8.setGeometry(QtCore.QRect(40, 140, 91, 21))
        self.label_8.setObjectName("label_8")
        self.connect_button = QtWidgets.QPushButton(self.Settings)
        self.connect_button.setGeometry(QtCore.QRect(20, 20, 141, 25))
        self.connect_button.setObjectName("connect_button")
        self.UID = QtWidgets.QLabel(self.Settings)
        self.UID.setGeometry(QtCore.QRect(130, 60, 301, 21))
        self.UID.setObjectName("UID")
        self.rf_power_text = QtWidgets.QLabel(self.Settings)
        self.rf_power_text.setGeometry(QtCore.QRect(120, 140, 67, 21))
        self.rf_power_text.setObjectName("rf_power_text")
        self.read_uuid = QtWidgets.QPushButton(self.Settings)
        self.read_uuid.setGeometry(QtCore.QRect(20, 60, 89, 25))
        self.read_uuid.setObjectName("read_uuid")
        self.tabWidget.addTab(self.Settings, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tab_position.setCurrentIndex(1)
        self.sweep_type.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VR Haptics"))
        self.label.setText(_translate("MainWindow", "Multi-\n"
"Modal"))
        self.label_3.setText(_translate("MainWindow", "   3D\n"
"Touch"))
        self.label_2.setText(_translate("MainWindow", "Single\n"
"Pulse"))
        self.h_dc_text.setText(_translate("MainWindow", "Intensity: 50 %"))
        self.pulse_Hfreq_text.setText(_translate("MainWindow", "Pulsing Frequency: 100 Hz"))
        self.single_pulse_dur_label.setText(_translate("MainWindow", "Single Pulse Duration(ms): "))
        self.all_off.setText(_translate("MainWindow", "ALL OFF"))
        self.label_4.setText(_translate("MainWindow", "Continuous"))
        self.hf_mod.setText(_translate("MainWindow", "Pulsing (High Freq modulation)"))
        self.lf_mod.setText(_translate("MainWindow", "Repeated Pulse\n"
"(Low Freq modulation)"))
        self.single_pulse_dur_text.setText(_translate("MainWindow", "500"))
        self.pulse_Lfreq_text.setText(_translate("MainWindow", "Repeated Pulse Frequency: 2 Hz"))
        self.l_dc_text.setText(_translate("MainWindow", "Intensity: 50 %"))
        self.set_time.setText(_translate("MainWindow", "Set Timing"))
        self.active_selected.setText(_translate("MainWindow", "Activate Selected"))
        self.append_preset.setText(_translate("MainWindow", "Append to preset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Manual), _translate("MainWindow", "Manual"))
        self.preset_button.setText(_translate("MainWindow", "Activate Preset"))
        self.sweep_type.setCurrentText(_translate("MainWindow", "Left to Right (LR)"))
        self.sweep_type.setItemText(0, _translate("MainWindow", "Left to Right (LR)"))
        self.sweep_type.setItemText(1, _translate("MainWindow", "Right to Left (RL)"))
        self.sweep_type.setItemText(2, _translate("MainWindow", "Top to Bottom (TB)"))
        self.sweep_type.setItemText(3, _translate("MainWindow", "Bottom to Top (BT)"))
        self.sweep_type.setItemText(4, _translate("MainWindow", "+45º BT"))
        self.sweep_type.setItemText(5, _translate("MainWindow", "+45º TB"))
        self.sweep_type.setItemText(6, _translate("MainWindow", "-45º BT"))
        self.sweep_type.setItemText(7, _translate("MainWindow", "-45º TB"))
        self.sweep_type.setItemText(8, _translate("MainWindow", "Explosion"))
        self.sweep_type.setItemText(9, _translate("MainWindow", "Implosion"))
        self.tab_position.setTabText(self.tab_position.indexOf(self.tab_2), _translate("MainWindow", "Sweeping"))
        self.tab_position.setTabText(self.tab_position.indexOf(self.tab_3), _translate("MainWindow", "ABCs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Automatic), _translate("MainWindow", "Automatic"))
        self.PORT.setText(_translate("MainWindow", "Serial Port:"))
        self.label_8.setText(_translate("MainWindow", "RF Power:"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.UID.setText(_translate("MainWindow", "UID:  XX XX XX XX XX XX XX XX"))
        self.rf_power_text.setText(_translate("MainWindow", "4 Watts"))
        self.read_uuid.setText(_translate("MainWindow", "Read UID"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("MainWindow", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
